spring.application.name=runly

# Banco de dados PostgreSQL na Nuvem (Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.habfxhnhnadhrnydpvet.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Runly@261105}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# Uploads & Multipart
runly.upload.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary (Hospedagem de Imagens)
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:afigevng}
cloudinary.api-key=${CLOUDINARY_API_KEY:436292776296816}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:nRl0Rv4aK6allF4fUu5bkpNN4dA}

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT
api.security.token.secret=${API_SECURITY_TOKEN_SECRET:runly-super-secret-key-prod-2026}
api.security.token.expiration-ms=86400000

# Porta da API
server.port=${PORT:8080}
