spring.application.name=runly

# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/runly
spring.datasource.username=postgres
spring.datasource.password=Vg@261105
spring.datasource.driver-class-name=org.postgresql.Driver

runly.upload.dir=uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT - troque esse segredo antes de publicar o projeto
api.security.token.secret=runly-super-secret-key-change-me
api.security.token.expiration-ms=86400000

# Porta da API
server.port=8080
